services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./src/lib/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  external:
    container_name: site
    image: site
    build:
      context: .
      dockerfile: Dockerfile
    user: "node"
    environment:
      - NODE_ENV=production
      - TZ=Pacific/Auckland
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 3000:5050

volumes:
  db:
    driver: local
