services:
  app:
    container_name: server
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 3000:3000
    # Enables functionality with CompileDaemon; see dev.Dockerfile
    volumes:
      - ./:/app 
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
  postgres:
    container_name: postgres-db
    image: postgres:17.2
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - 5432:5432
    volumes:
      - ./db/pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
